## Core
title: Diapsalmata
email: tanweerzakariya@gmail.com
description: >-
  Philosophical fragments...

  
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji


# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Some thoughts" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "/assets/header.png"




navigation_header:
  - title: Diapsalmata
    url: /
  - title: Tags
    url: /categories/
  - title: Search 
    url: /search/
  - title: About
    url: /about/




## Looks
remote_theme: daviddarnes/alembic@main
# remote_theme: broccolini/swiss

## Technicals
url: "https://zakariya.github.io/"
domain: "zakariya.github.io"
github_username: NotZakariya
lang: en-GB


