## Core
title: Diapsalmata
email: tanweerzakariya@gmail.com
description: >-
  Philosophical fragments...

navigation_header:
  - title: Diapsalmata
    url: /
  - title: About
    url: /about/
  - title: Tags
    url: /categories/
  - title: Search 
    url: /search/




## Looks
remote_theme: daviddarnes/alembic@main
# remote_theme: broccolini/swiss

## Technicals
url: "https://zakariya.github.io/"
domain: "zakariya.github.io"
github_username: NotZakariya
lang: en-GB

plugins:
  - jekyll-remote-theme
  - jekyll-feed
